source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HKProjectBase_Example', :exclusive => true do
  pod "HKProjectBase", :path => "../"
end

target 'HKProjectBase_Tests', :exclusive => true do
  pod "HKProjectBase", :path => "../"

  
end
